# viral_usher config for RefSeq NC_021544.1, taxonomy ID 3432195

viral_usher_version = '0.7.0'
refseq_acc = 'NC_021544.1'
refseq_assembly = 'GCF_000907835.1'
taxonomy_id = '3432195'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Human_rotavirus_B_6'
