# viral_usher config for RefSeq NC_009827.1, taxonomy ID 3052230

viral_usher_version = '0.7.0'
refseq_acc = 'NC_009827.1'
refseq_assembly = 'GCF_000872025.1'
taxonomy_id = '3052230'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Hepatitis_C_virus_genotype_6'
