# viral_usher config for RefSeq NC_001498.1, taxonomy ID 11234

viral_usher_version = '0.7.0'
refseq_acc = 'NC_001498.1'
refseq_assembly = 'GCF_000854845.1'
taxonomy_id = '11234'
nextclade_dataset = 'nextstrain/measles/N450/WHO-2012'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/measles'
