# viral_usher config for RefSeq NC_002728.1, taxonomy ID 3052225

viral_usher_version = '0.10.3'
#refseq_acc = 'NC_002728.1'
#refseq_assembly = 'GCF_000863625.1'
ref_fasta = './trees/Nipah_virus/treetime_rerooted_NC_002728.1.fa'
ref_gbff = './trees/Nipah_virus/treetime_rerooted_NC_002728.1.gbff'
update_tree_input = ''
update_metadata_input = ''
species = 'Nipah virus'
taxonomy_id = '3052225'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = ''
annotate_mask_frequency = ''
extra_fasta = ''
extra_metadata = ''
extra_metadata_date_column = ''
taxonium_overlay_html = ''
workdir = './trees/Nipah_virus'
