# viral_usher config for RefSeq NC_006024.2, taxonomy ID 3431240

viral_usher_version = '0.7.0'
refseq_acc = 'NC_006024.2'
refseq_assembly = 'GCF_000854445.2'
taxonomy_id = '3431240'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Bluetongue_virus_4'
