# viral_usher config for RefSeq NC_002058.3, taxonomy ID 3428505

viral_usher_version = '0.8.0'
refseq_acc = 'NC_002058.3'
refseq_assembly = 'GCF_000861165.1'
taxonomy_id = '3428505'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Enterovirus_C'
