# viral_usher config for RefSeq NC_039210.1, taxonomy ID 3426401

viral_usher_version = '0.7.0'
refseq_acc = 'NC_039210.1'
refseq_assembly = 'GCF_002816555.1'
taxonomy_id = '3426401'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Foot_and_mouth_disease_virus_O'
