# viral_usher config for RefSeq NC_014070.1, taxonomy ID 3048408

viral_usher_version = '0.8.0'
refseq_acc = 'NC_014070.1'
refseq_assembly = 'GCF_000888195.1'
taxonomy_id = '3048408'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Torque_teno_sus_virus_1a'
