# viral_usher config for RefSeq NC_004612.1, taxonomy ID 3426993

viral_usher_version = '0.8.0'
refseq_acc = 'NC_004612.1'
refseq_assembly = 'GCF_000842925.1'
taxonomy_id = '3426993'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Tomato_leaf_curl_New_Delhi_virus_DNA_B'
