# viral_usher config for RefSeq NC_075404.1, taxonomy ID 3051375

viral_usher_version = '0.7.0'
refseq_acc = 'NC_075404.1'
refseq_assembly = 'GCF_004786615.1'
taxonomy_id = '3051375'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Avian_orthoavulavirus_1_chicken_N_Ireland_Ulster_67'
