# viral_usher config for RefSeq NC_001440.1, taxonomy ID 3428131

viral_usher_version = '0.8.0'
refseq_acc = 'NC_001440.1'
refseq_assembly = 'GCF_000864745.1'
taxonomy_id = '3428131'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Cucumber_mosaic_virus_RNA_3'
