# viral_usher config for RefSeq NC_074955.1, taxonomy ID 1678143

viral_usher_version = '0.8.0'
refseq_acc = 'NC_074955.1'
refseq_assembly = 'GCF_002826225.1'
taxonomy_id = '1678143'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Paslahepevirus_balayani_NC_074955_1'
