# viral_usher config for RefSeq NC_014037.1, taxonomy ID 3431714

viral_usher_version = '0.8.0'
refseq_acc = 'NC_014037.1'
refseq_assembly = 'GCF_000887195.1'
taxonomy_id = '3431714'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Sugarcane_streak_mosaic_virus'
