# viral_usher config for RefSeq NC_038235.1, taxonomy ID 3049954

viral_usher_version = '0.10.0'
#refseq_acc = 'NC_038235.1'
#refseq_assembly = 'GCF_002815475.1'
ref_fasta = './trees/Human_orthopneumovirus_NC_038235_1/midpoint_rerooted_NC_038235.1.fa'
ref_gbff = './trees/Human_orthopneumovirus_NC_038235_1/midpoint_rerooted_NC_038235.1.gbff'
taxonomy_id = '3049954'
nextclade_dataset = 'nextstrain/rsv/a/EPI_ISL_412866'
nextclade_clade_columns = 'clade,phenotypeData'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = '0.99'
annotate_mask_frequency = '0.1'
extra_fasta = ''
workdir = './trees/Human_orthopneumovirus_NC_038235_1'
