# viral_usher config for RefSeq NC_001608.4, taxonomy ID 3052505

viral_usher_version = '0.10.3'
#refseq_acc = 'NC_001608.4'
#refseq_assembly = 'GCF_000857325.3'
ref_fasta = './trees/Marburg_virus/treetime_rerooted_NC_001608.4.fa'
ref_gbff = './trees/Marburg_virus/treetime_rerooted_NC_001608.4.gbff'
update_tree_input = ''
update_metadata_input = ''
species = 'Marburg virus'
taxonomy_id = '3052505'
nextclade_dataset = 'community/genspectrum/marburg/HK1980/all-lineages'
nextclade_clade_columns = 'clade,lineage'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = '0.99'
annotate_mask_frequency = '0.1'
extra_fasta = ''
extra_metadata = ''
extra_metadata_date_column = ''
taxonium_overlay_html = ''
workdir = './trees/Marburg_virus'
