# viral_usher config for RefSeq NC_007366.1, taxonomy ID 2955291

viral_usher_version = '0.7.0'
refseq_acc = 'NC_007366.1'
refseq_assembly = 'GCF_000865085.1'
taxonomy_id = '2955291'
nextclade_dataset = 'nextstrain/flu/h3n2/ha/CY163680'
nextclade_clade_columns = 'clade,proposedSubclade,short-clade,subclade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Influenza_A_virus_A_New_York_392_2004_H3N2_4'
