# viral_usher config for RefSeq NC_001815.1, taxonomy ID 3428213

viral_usher_version = '0.8.0'
refseq_acc = 'NC_001815.1'
refseq_assembly = 'GCF_000860005.1'
taxonomy_id = '3428213'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Simian_T_lymphotropic_virus_2'
