# viral_usher config for RefSeq NC_004667.1, taxonomy ID 3426349

viral_usher_version = '0.7.0'
refseq_acc = 'NC_004667.1'
refseq_assembly = 'GCF_000851885.1'
taxonomy_id = '3426349'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Grapevine_leafroll_associated_virus_3'
