# viral_usher config for RefSeq NC_000855.1, taxonomy ID 1980916

viral_usher_version = '0.7.0'
refseq_acc = 'NC_000855.1'
refseq_assembly = 'GCF_000856505.1'
taxonomy_id = '1980916'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Viral_hemorrhagic_septicemia_virus_Fil3'
