# viral_usher config for RefSeq NC_001475.2, taxonomy ID 3052464

viral_usher_version = '0.10.0'
#refseq_acc = 'NC_001475.2'
#refseq_assembly = 'GCF_000866625.1'
ref_fasta = './trees/dengue_virus_type_3/treetime_rerooted_NC_001475.2.fa'
ref_gbff = './trees/dengue_virus_type_3/treetime_rerooted_NC_001475.2.gbff'
taxonomy_id = '3052464'
nextclade_dataset = 'community/v-gen-lab/dengue/denv3'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = '0.99'
annotate_mask_frequency = '0.1'
extra_fasta = ''
workdir = './trees/dengue_virus_type_3'
