# viral_usher config for RefSeq NC_007362.1, taxonomy ID 2955291

viral_usher_version = '0.7.0'
refseq_acc = 'NC_007362.1'
refseq_assembly = 'GCF_000864105.1'
taxonomy_id = '2955291'
nextclade_dataset = 'community/moncla-lab/iav-h5/ha/all-clades'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Influenza_A_virus_A_goose_Guangdong_1_1996_H5N1_4'
