# viral_usher config for RefSeq NC_029647.1, taxonomy ID 3431196

viral_usher_version = '0.7.0'
refseq_acc = 'NC_029647.1'
refseq_assembly = 'GCF_001595715.1'
taxonomy_id = '3431196'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Norovirus_GIV_Hu_GIV_1_LakeMacquarie_NSW268O_2010_AU'
