# viral_usher config for RefSeq NC_038291.1, taxonomy ID 2499685

viral_usher_version = '0.7.0'
refseq_acc = 'NC_038291.1'
refseq_assembly = 'GCF_002816115.1'
taxonomy_id = '2499685'
nextclade_dataset = 'community/isuvdl/mazeller/prrsv2/orf5/yimim2023'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Porcine_reproductive_and_respiratory_syndrome_virus_2'
