# viral_usher config for RefSeq NC_009942.1, taxonomy ID 3048448

viral_usher_version = '0.10.0'
#refseq_acc = 'NC_009942.1'
#refseq_assembly = 'GCF_000875385.1'
ref_fasta = './trees/West_Nile_virus_385_99/treetime_rerooted_NC_009942.1.fa'
ref_gbff = './trees/West_Nile_virus_385_99/treetime_rerooted_NC_009942.1.gbff'
taxonomy_id = '3048448'
nextclade_dataset = 'nextstrain/wnv/all-lineages'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/West_Nile_virus_385_99'
