# viral_usher config for RefSeq NC_001653.2, taxonomy ID 2844074

viral_usher_version = '0.8.0'
refseq_acc = 'NC_001653.2'
refseq_assembly = 'GCF_000856565.1'
taxonomy_id = '2844074'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Hepatitis_delta_virus_NC_001653_2'
