# viral_usher config for RefSeq NC_003623.1, taxonomy ID 3047852

viral_usher_version = '0.8.0'
refseq_acc = 'NC_003623.1'
refseq_assembly = 'GCF_000860305.1'
taxonomy_id = '3047852'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Grapevine_fanleaf_virus_NC_003623_1'
