# viral_usher config for RefSeq NC_001474.2, taxonomy ID 11060

viral_usher_version = '0.7.0'
refseq_acc = 'NC_001474.2'
refseq_assembly = 'GCF_000871845.1'
taxonomy_id = '11060'
nextclade_dataset = 'community/v-gen-lab/dengue/denv2'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/dengue_2'
