# viral_usher config for RefSeq NC_075105.1, taxonomy ID 342409

viral_usher_version = '0.8.0'
refseq_acc = 'NC_075105.1'
refseq_assembly = 'GCF_003024735.1'
taxonomy_id = '342409'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Shrimp_white_spot_syndrome_virus'
