# viral_usher config for RefSeq NC_002532.2, taxonomy ID 2499620

viral_usher_version = '0.8.0'
refseq_acc = 'NC_002532.2'
refseq_assembly = 'GCF_000860865.1'
taxonomy_id = '2499620'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Equine_arteritis_virus'
