# viral_usher config for RefSeq NC_039218.1, taxonomy ID 3048170

viral_usher_version = '0.10.3'
#refseq_acc = 'NC_039218.1'
#refseq_assembly = 'GCF_002820625.1'
ref_fasta = './trees/Kyasanur_Forest_disease_virus/treetime_rerooted_NC_039218.1.fa'
ref_gbff = './trees/Kyasanur_Forest_disease_virus/treetime_rerooted_NC_039218.1.gbff'
update_tree_input = ''
update_metadata_input = ''
species = 'Kyasanur Forest disease virus'
taxonomy_id = '3048170'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = ''
annotate_mask_frequency = ''
extra_fasta = ''
extra_metadata = ''
extra_metadata_date_column = ''
taxonium_overlay_html = ''
workdir = './trees/Kyasanur_Forest_disease_virus'
