# viral_usher config for RefSeq NC_001781.1, taxonomy ID 3049954

viral_usher_version = '0.7.0'
refseq_acc = 'NC_001781.1'
refseq_assembly = 'GCF_000855545.1'
taxonomy_id = '3049954'
nextclade_dataset = 'nextstrain/rsv/b/EPI_ISL_1653999'
nextclade_clade_columns = 'clade,phenotypeData'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Human_orthopneumovirus_B1'
