# viral_usher config for RefSeq NC_002361.1, taxonomy ID 3050342

viral_usher_version = '0.8.0'
refseq_acc = 'NC_002361.1'
refseq_assembly = 'GCF_000843885.1'
taxonomy_id = '3050342'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Columbid_circovirus'
