# viral_usher config for RefSeq NC_015783.1, taxonomy ID 68887

viral_usher_version = '0.7.0'
refseq_acc = 'NC_015783.1'
refseq_assembly = 'GCF_000893775.1'
taxonomy_id = '68887'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Torque_teno_virus_TTV_HD14a_gbDhDi33_32'
