# viral_usher config for RefSeq NC_030454.1, taxonomy ID 3428500

viral_usher_version = '0.7.0'
refseq_acc = 'NC_030454.1'
refseq_assembly = 'GCF_001684625.1'
taxonomy_id = '3428500'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/enterovirus_A114'
