# viral_usher config for RefSeq NC_076339.1, taxonomy ID 93678

viral_usher_version = '0.7.0'
refseq_acc = 'NC_076339.1'
refseq_assembly = 'GCF_018584815.1'
taxonomy_id = '93678'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/TTV_like_mini_virus_vzttmv4'
