# viral_usher config for RefSeq NC_013397.1, taxonomy ID 3431252

viral_usher_version = '0.7.0'
refseq_acc = 'NC_013397.1'
refseq_assembly = 'GCF_000885335.1'
taxonomy_id = '3431252'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Epizootic_hemorrhagic_disease_virus_serotype_1_strain_New_Jersey_2'
