# viral_usher config for RefSeq NC_001612.1, taxonomy ID 3428500

viral_usher_version = '0.10.0'
#refseq_acc = 'NC_001612.1'
#refseq_assembly = 'GCF_000861905.1'
ref_fasta = './trees/Enterovirus_A/treetime_rerooted_NC_001612.1.fa'
ref_gbff = './trees/Enterovirus_A/treetime_rerooted_NC_001612.1.gbff'
taxonomy_id = '3428500'
nextclade_dataset = 'enpen/enterovirus/cva16'
nextclade_clade_columns = 'clade,mutLabels'
annotate_allele_frequency = '0.999'
annotate_mask_frequency = '0.1'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Enterovirus_A'
