# viral_usher config for RefSeq NC_003462.2, taxonomy ID 35350

viral_usher_version = '0.8.0'
refseq_acc = 'NC_003462.2'
refseq_assembly = 'GCF_000850465.1'
taxonomy_id = '35350'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Foveavirus_mali'
