"""
For every trees/ subdirectory, read its all.rtt.tsv file (generated by root_to_tip.py).
Combine results for all rerooting methods into one row of tsv output.
"""

import argparse
import csv
import os
import sys

import viral_usher_trees

rtt_required_columns = ["method", "r_squared", "slope"]


def read_one_tsv(tree: str):
    tsv_path = "/".join([viral_usher_trees.trees_dir, tree, "all.rtt.tsv"])
    results = {'midpoint_r_squared': '', 'midpoint_slope': '',
               'treetime_r_squared': '', 'treetime_slope': '',
               'outgroup_r_squared': '', 'outgroup_slope': ''}
    max_r_squared = None
    with open(tsv_path) as f:
        reader = csv.DictReader(f, delimiter='\t')
        fieldnames = reader.fieldnames
        viral_usher_trees.check_required_columns(fieldnames, rtt_required_columns, tsv_path)
        for row in reader:
            method = row['method']
            if method not in ['midpoint', 'treetime', 'outgroup']:
                print(f"Unrecognized method {method} in {tsv_path}", file=sys.stderr)
                sys.exit(1)
            results[method + '_r_squared'] = row['r_squared']
            results[method + '_slope'] = row['slope']
            r_squared = float(row['r_squared'])
            if max_r_squared is None or r_squared >= max_r_squared:
                max_r_squared = r_squared
    best_methods = []
    for method in ['midpoint', 'treetime', 'outgroup']:
        if results[method + '_r_squared']:
            r_squared = float(results[method + '_r_squared'])
            if r_squared == max_r_squared:
                best_methods.append(method)
    summary = [tree, ",".join(best_methods), 'plot',
               'midpoint', results['midpoint_r_squared'], results['midpoint_slope'],
               'treetime', results['treetime_r_squared'], results['treetime_slope'],
               'outgroup', results['outgroup_r_squared'], results['outgroup_slope']]
    return summary


def main():
    parser = argparse.ArgumentParser(description="Collect trees/*/all.rtt.tsv, output TSV with one line per tree.")
    parser.add_argument('-o', '--output', required=True,
                        help="Output TSV file")
    args = parser.parse_args()
    viral_usher_trees.check_top_level_dir()
    trees = [d
             for d in os.listdir(viral_usher_trees.trees_dir)
             if os.path.isdir("/".join([viral_usher_trees.trees_dir, d]))]
    trees.sort()
    with open(args.output, "w") as f:
        f.write("\t".join(["tree", "best_r_squared_methods", "rtt_plot_label",
                           "midpoint_label", "midpoint_r_squared", "midpoint_slope",
                           "treetime_label", "treetime_r_squared", "treetime_slope",
                           "outgroup_label", "outgroup_r_squared", "outgroup_slope"]) + "\n")
        for tree in trees:
            summary = read_one_tsv(tree)
            f.write("\t".join(summary) + "\n")


if __name__ == "__main__":
    main()
