# viral_usher config for RefSeq NC_075135.1, taxonomy ID 3430734

viral_usher_version = '0.8.0'
refseq_acc = 'NC_075135.1'
refseq_assembly = 'GCF_003048235.1'
taxonomy_id = '3430734'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Maize_streak_virus_A_South_Africa'
