# viral_usher config for RefSeq NC_003736.1, taxonomy ID 3428768

viral_usher_version = '0.8.0'
refseq_acc = 'NC_003736.1'
refseq_assembly = 'GCF_000852945.1'
taxonomy_id = '3428768'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Rice_black_streaked_dwarf_virus_5'
