# viral_usher config for RefSeq NC_001348.1, taxonomy ID 3050294

viral_usher_version = '0.10.0'
#refseq_acc = 'NC_001348.1'
#refseq_assembly = 'GCF_000858285.1'
ref_fasta = './trees/Human_alphaherpesvirus_3/treetime_rerooted_NC_001348.1.fa'
ref_gbff = './trees/Human_alphaherpesvirus_3/treetime_rerooted_NC_001348.1.gbff'
taxonomy_id = '3050294'
nextclade_dataset = 'nextstrain/herpes/vzv/NC_001348'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = '0.99'
annotate_mask_frequency = '0.1'
extra_fasta = ''
workdir = './trees/Human_alphaherpesvirus_3'
