# viral_usher config for RefSeq NC_001477.1, taxonomy ID 11053

viral_usher_version = '0.7.0'
refseq_acc = 'NC_001477.1'
refseq_assembly = 'GCF_000862125.1'
taxonomy_id = '11053'
nextclade_dataset = 'community/v-gen-lab/dengue/denv1'
nextclade_clade_columns = 'clade'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/dengue_1'
