# viral_usher config for RefSeq NC_002306.3, taxonomy ID 3433814

viral_usher_version = '0.7.0'
refseq_acc = 'NC_002306.3'
refseq_assembly = 'GCF_000856025.1'
taxonomy_id = '3433814'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Feline_infectious_peritonitis_virus'
