# viral_usher config for RefSeq NC_005776.1, taxonomy ID 3052429

viral_usher_version = '0.7.0'
refseq_acc = 'NC_005776.1'
refseq_assembly = 'GCF_000853785.1'
taxonomy_id = '3052429'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Oropouche_virus_L'
