# viral_usher config for RefSeq NC_006577.2, taxonomy ID 3433758

viral_usher_version = '0.10.3'
#refseq_acc = 'NC_006577.2'
#refseq_assembly = 'GCF_000858765.1'
ref_fasta = './trees/Human_coronavirus_HKU1/treetime_rerooted_NC_006577.2.fa'
ref_gbff = './trees/Human_coronavirus_HKU1/treetime_rerooted_NC_006577.2.gbff'
update_tree_input = ''
update_metadata_input = ''
species = 'Human coronavirus HKU1'
taxonomy_id = '3433758'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = ''
annotate_mask_frequency = ''
extra_fasta = ''
extra_metadata = ''
extra_metadata_date_column = ''
taxonium_overlay_html = ''
workdir = './trees/Human_coronavirus_HKU1'
