# viral_usher config for RefSeq NC_043450.1, taxonomy ID 2748958

viral_usher_version = '0.8.0'
refseq_acc = 'NC_043450.1'
refseq_assembly = 'GCF_003087855.1'
taxonomy_id = '2748958'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Severe_fever_with_thrombocytopenia_syndrome_virus_L'
