# viral_usher config for RefSeq NC_001409.1, taxonomy ID 12175

viral_usher_version = '0.8.0'
refseq_acc = 'NC_001409.1'
refseq_assembly = 'GCF_000848285.1'
taxonomy_id = '12175'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Trichovirus_mali'
