# viral_usher config for RefSeq NC_002200.1, taxonomy ID 3052560

viral_usher_version = '0.7.0'
refseq_acc = 'NC_002200.1'
refseq_assembly = 'GCF_000856685.1'
taxonomy_id = '3052560'
nextclade_dataset = 'nextstrain/mumps/genome'
nextclade_clade_columns = 'clade,MuV_genotype'
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Mumps_orthorubulavirus'
