# viral_usher config for RefSeq NC_003467.2, taxonomy ID 1980456

viral_usher_version = '0.10.3'
#refseq_acc = 'NC_003467.2'
#refseq_assembly = 'GCF_000850405.1'
ref_fasta = './trees/Orthohantavirus_andesense_M/treetime_rerooted_NC_003467.2.fa'
ref_gbff = './trees/Orthohantavirus_andesense_M/treetime_rerooted_NC_003467.2.gbff'
update_tree_input = ''
update_metadata_input = ''
species = 'Orthohantavirus andesense'
taxonomy_id = '1980456'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = ''
annotate_mask_frequency = ''
extra_fasta = ''
extra_metadata = ''
extra_metadata_date_column = ''
taxonium_overlay_html = ''
title = ''
workdir = '/cluster/home/angie/github/viral_usher_trees/trees/Orthohantavirus_andesense_M'
