# viral_usher config for RefSeq NC_038308.1, taxonomy ID 3428506

viral_usher_version = '0.10.0'
#refseq_acc = 'NC_038308.1'
#refseq_assembly = 'GCF_002816725.1'
ref_fasta = './trees/enterovirus_D68/treetime_rerooted_NC_038308.1.fa'
ref_gbff = './trees/enterovirus_D68/treetime_rerooted_NC_038308.1.gbff'
taxonomy_id = '3428506'
nextclade_dataset = 'enpen/enterovirus/ev-d68'
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/enterovirus_D68'
