# viral_usher config for RefSeq NC_019843.3, taxonomy ID 3433633

viral_usher_version = '0.7.0'
refseq_acc = 'NC_019843.3'
refseq_assembly = 'GCF_000901155.1'
taxonomy_id = '3433633'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Middle_East_respiratory_syndrome_related_coronavirus'
