# viral_usher config for RefSeq NC_002549.1, taxonomy ID 3052462

viral_usher_version = '0.10.0'
#refseq_acc = 'NC_002549.1'
#refseq_assembly = 'GCF_000848505.1'
ref_fasta = './trees/Zaire_ebolavirus/treetime_rerooted_NC_002549.1.fa'
ref_gbff = './trees/Zaire_ebolavirus/treetime_rerooted_NC_002549.1.gbff'
taxonomy_id = '3052462'
nextclade_dataset = 'nextstrain/orthoebolavirus/ebov'
nextclade_clade_column = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
annotate_allele_frequency = '0.99'
annotate_mask_frequency = '0.1'
extra_fasta = ''
workdir = './trees/Zaire_ebolavirus'
