# viral_usher config for RefSeq NC_001575.2, taxonomy ID 3432506

viral_usher_version = '0.8.0'
refseq_acc = 'NC_001575.2'
refseq_assembly = 'GCF_000863085.1'
taxonomy_id = '3432506'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Rice_yellow_mottle_virus'
