# viral_usher config for RefSeq NC_006383.2, taxonomy ID 3052343

viral_usher_version = '0.7.0'
refseq_acc = 'NC_006383.2'
refseq_assembly = 'GCF_000866445.1'
taxonomy_id = '3052343'
nextclade_dataset = ''
nextclade_clade_columns = ''
min_length_proportion = '0.8'
max_N_proportion = '0.25'
max_parsimony = '1000'
max_branch_length = '10000'
extra_fasta = ''
workdir = './trees/Peste_des_petits_ruminants_virus'
